name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
        name: Install npm packages
      - name: Install UCPeM ports
        run: curl -L https://github.com/bt7s7k7/UCPeM/releases/latest/download/ucpem.js | node - install
      - run: npm run build
        name: Build typescript
      - run: npm run test
        name: Run test script
